# Generated by Django 6.0.7 on 2026-07-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_profile_img_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='default_user.jpg', upload_to='avtrs/'),
        ),
    ]
