# Generated by Django 6.0.7 on 2026-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
