# Generated by Django 6.0.7 on 2026-07-19 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentinfo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
