# Generated by Django 6.0.7 on 2026-07-17 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
